export type IconName =
'chatbot'
  | 'home'
  | 'docs'
  | 'docs-fill'
  | 'chat-fill'
  | 'mypage'
  | 'chat'
  | 'close'
  | 'close-circle'
  | 'contract'
  | 'message'
  | 'exclamation'
  | 'check'
  | 'chev-left'
  | 'chev-right'
  | 'bell'
  | 'docs'
  | 'copy'
  | 'zoom-in';